sudo: required

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements-dev.txt
  - pip install coveralls

script:
  - flake8 setup.py lewis scripts system-tests test
  - pytest --cov=lewis.core --cov=lewis.devices test
  - pytest system_tests/lewis_tests.py
  - sphinx-build -W -b html docs/ docs/_build/html

after_success:
  - coveralls

branches:
  only:
    - master
