sudo: required

language: python

services:
  - docker

python:
  - "2.7"
  - "3.5"

install:
  - pip install -e ".[dev]"

script:
  - flake8 .
  - pytest --cov=lewis.core --cov=lewis.devices test
  - sphinx-build -b html docs/ docs/_build/html

after_success:
  - coveralls
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == false ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker build -t dmscid/lewis:edge .;
    docker push dmscid/lewis:edge;
    fi

branches:
  only:
    - master
