---
image:
  - Visual Studio 2019
  - Ubuntu


environment:
  matrix:
  - TOXENV: py36
  - TOXENV: py37
  - TOXENV: py38

build: off

install:
- sh: python -m venv myenv
- sh: source myenv/bin/activate
- python -m pip install tox

test_script:
- tox
